name: Verify Build
on: [push]
jobs:
  Verify-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Download FuseSoC
        run: |
          python -m pip install --upgrade pip
          pip install fusesoc
          fusesoc --version
      - name: Download OSS
        run: |
          curl -JOL https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-04-30/oss-cad-suite-linux-x64-20230430.tgz
          tar -xzvf oss-cad-suite-linux-x64-20230430.tgz -C ./
          rm -rf oss-cad-suite-linux-x64-20230430.tgz
          echo "$GITHUB_WORKSPACE/oss-cad-suite/bin" >> $GITHUB_PATH
      - name: Init FuseSoC
        run: fusesoc library add sifferman__nes_controller_interface . --sync-type=local
      - name: Lint with Verilator
        run: fusesoc run --target lint sifferman::nes_controller_interface
      - name: Simulate with Icarus
        run: fusesoc run --target sim --tool icarus sifferman::nes_controller_interface
      - name: Simulate with Verilator
        run: fusesoc run --target sim --tool verilator sifferman::nes_controller_interface
      - name: Synthesize controller with Icestorm for the iCE40HX-8K CT256
        run: fusesoc run --target synth_controller sifferman::nes_controller_interface
      - name: Synthesize controller interface with Icestorm for the iCE40HX-8K CT256
        run: fusesoc run --target synth_interface sifferman::nes_controller_interface
